In [2]:
import numpy as np

In [3]:
A = {"x1":0.2, "x2":0.7, "x3":0.5}
B = {"x1":0.6, "x2":0.3, "x3":0.9}

In [4]:
union       = {x: max(A[x], B[x]) for x in A}
intersect   = {x: min(A[x], B[x]) for x in A}
complementA = {x: round(1-A[x],2) for x in A}
difference  = {x: min(A[x], 1-B[x]) for x in A}

In [5]:
print("Union:", union)
print("Intersection:", intersect)
print("Complement A:", complementA)
print("Difference A-B:", difference)

Union: {'x1': 0.6, 'x2': 0.7, 'x3': 0.9}
Intersection: {'x1': 0.2, 'x2': 0.3, 'x3': 0.5}
Complement A: {'x1': 0.8, 'x2': 0.3, 'x3': 0.5}
Difference A-B: {'x1': 0.2, 'x2': 0.7, 'x3': 0.09999999999999998}


In [6]:
# Cartesian product -> Fuzzy relations
R = np.array([[min(a,b) for b in B.values()] for a in A.values()])
S = np.array([[min(a,b) for b in A.values()] for a in B.values()])
print("\nR = A x B:\n", R)
print("S = B x A:\n", S)


R = A x B:
 [[0.2 0.2 0.2]
 [0.6 0.3 0.7]
 [0.5 0.3 0.5]]
S = B x A:
 [[0.2 0.6 0.5]
 [0.2 0.3 0.3]
 [0.2 0.7 0.5]]


In [7]:
# Max-Min composition
T = np.zeros((R.shape[0], S.shape[1]))
for i in range(R.shape[0]):
    for j in range(S.shape[1]):
        T[i][j] = max(min(R[i][k], S[k][j]) for k in  range(R.shape[1]))
print("\nMax-Min Composition R o S:\n", T)


Max-Min Composition R o S:
 [[0.2 0.2 0.2]
 [0.2 0.7 0.5]
 [0.2 0.5 0.5]]
